import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import Hero from "./ui/hero";
import Footer from "./Footer";

const archivo = Archivo({ subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "NOR-BUD od 2021 r. Zmieniamy Polskę",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pl">
      <body className={archivo.className}>
        <Hero bg={"bg-hero-1"} />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
