import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import Hero from "./ui/hero";
import getData from "./lib/getData";
import { companyInfoRequest } from "./data/company-info-request";

const archivo = Archivo({ subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "NOR-BUD od 2021 r. Zmieniamy Polskę",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  let data = await getData(companyInfoRequest.URL);
  let aboutUsHeading = data.acf.aboutUsHeading;

  return (
    <html lang="pl">
      <body className={archivo.className}>
        <Hero aboutUsHeading={aboutUsHeading} bg={"bg-hero-1"} />
        <main>{children}</main>
        <footer>@ 2024 Norbud. All rights reserved.</footer>
      </body>
    </html>
  );
}
